blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, verbose_name='Название поста')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts', verbose_name='Автор')
    short_description=models.CharField(max_length=400, verbose_name='Краткое описание')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статус публикации')
    image = models.ImageField(upload_to='product_images/', blank=False, verbose_name='Изображение')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                             self.publish.month,
                                             self.publish.day,
                                             self.slug])



def save_images(instance, filename):
    post_id = instance.post.id
    return 'gallery_images/{}/{}'.format(post_id, filename)


class PostPoint(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    post_point_text = models.TextField(verbose_name='Пункт поста')
    post_images = models.ImageField(upload_to=save_images, blank=True,
                                    verbose_name='Изображение пункта',)

    def __str__(self):
        return 'Пункт поста {}'.format(self.post.title)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Коментарий написан {} о {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'id': 'nameInput'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'id': 'exampleInputEmail1',
                                                           'aria-describedby': 'emailHelp'}))
    to = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                 'id': 'emailTo'}))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control',
                                                                           'id': 'comments',
                                                                           'rows': '3'}))

class CommentForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'id': 'nameInput'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={"class": "form-control",
                                                           "id": "exampleInputEmail1",
                                                           "aria-describedby": "emailHelp"
                                                           }))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control",
                                                                            "id": "comments",
                                                                            "rows": "3"}))

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

# Create your views here.
from .models import Post, PostPoint
from .forms import EmailPostForm, CommentForm


def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})


class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post_object = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    post_points = PostPoint.objects.filter(post=post_object)

    comments = post_object.comment.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post_object,
                                                     'post_points': post_points,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form
                                                     })

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_url(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)

            message = 'Read "{}" at {} \n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comment'])
            send_mail(subject, message, 'admin@blog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form})

blog/templates/blog/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <title>{%block title%} {% endblock %}</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>


   {% block navbar %}
     <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
         <a class="navbar-brand" href="#">Navbar</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav mr-auto">
                 <li class="nav-item active">
                     <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="#">Link</a>
                 </li>
                 <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         Dropdown
                     </a>
                     <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                         <a class="dropdown-item" href="#">Action</a>
                         <a class="dropdown-item" href="#">Another action</a>
                         <div class="dropdown-divider"></div>
                         <a class="dropdown-item" href="#">Something else here</a>
                     </div>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                 </li>
             </ul>
             <form class="form-inline my-2 my-lg-0">
                 <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                 <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
             </form>
         </div>
     </nav>
   {% endblock %}

   {%block content%}
     <h1>Content</h1>
   {% endblock %}



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>

</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}


    <div class="container my-3">
        <div class="card-deck">
            <div class="card">
                <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.short_description }}</p>
                    <p>
                        <a href="{% url "blog:post_share" post.id %}">Поделиться рецептом</a>
                    </p>

                </div>
                {% for post_point in post_points %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post_point.post_point_header}}</h5>
                        {% if post_point.post_image %}
                            <img src="{{ MEDIA_URL }}{{ post_point.post_image.url }}" class="card-img-top" alt="..."
                            style="width: 500px">
                        {% endif %}
                        {% if post_point.post_point_header == "Ингридиенты" %}
                            <pre class="card-text">{{ post_point.post_point_text }}</pre>
                        {% else %}
                            <p class="card-text">{{ post_point.post_point_text }}</p>
                        {% endif %}

                    </div>
                {% endfor %}
                <div class="card-footer">
                    <small class="text-muted">Опубликовано {{ post.publish }}. Автор {{ post.author }}</small>
                </div>
            </div>
        </div>
    </div>
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}



    {% with comments.count as total_comments  %}
        <h2>{{ total_comments }} коментариев</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="card border-dark mb-3" >
          <div class="card-header"><b>{{ forloop.counter }}. </b> {{ comment.name }},  E-mail {{ comment.email }}</div>
           <div class="card-body  text-dark">
            <p class="card-text">{{ comment.body }}</p>
          </div>
        </div>
    {% endfor %}
    <div class="m-5">
        {% if new_comment %}
            <h2>Ваш комментарий добавлен</h2>
        {% else %}
            <h2>Добавить комментарий</h2>
            <form action="." method="post">
            <div class="form-group">
                <label for="nameInput">Имя</label>
                {{ comment_form.name }}
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Ваш Email </label>
                {{ comment_form.email }}
            </div>
            <div class="form-group">
                <label for="comment">Комментарий</label>
                {{ comment_form.comment }}
            </div>
            <button type="submit" class="btn btn-primary">Добавить комментарий</button>
            {% csrf_token %}
            </form>
        {% endif %}
    </div>


{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1 class="title text-center my-3">Кулінарна книга</h1>
    <div class="container">
        <div class="card-deck">
            {% for post in posts %}
                <div class="card">
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">

                    </a>
                    <div class="card-body">
                        <a href="{{ post.get_absolute_url }}">
                            <h5 class="card-title">{{ post.title }}</h5>

                        </a>
                        <p class="card-text">{{ post.short_descriptions }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Опубликовано  {{post.publish}} автор : {{post.author}}</small>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>



{% include "paginations.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    <div class="container">
        {% if sent %}
            <h1>E-mail успешно отправлен</h1>
            <p>"{{ post.title }}" было успешно отправлено {{ form.cleaned_data.to }}.</p>
        {% else %}
            <h1>"{{ post.title }}"Будет Отправлено по e-mail</h1>
            <form action="." method="post">
                <div class="form-group">
                    <label for="nameInput">Имя</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Ваш Email </label>
                    {{ form.email }}
                    <small id="emailHelp" class="form-text text-muted">Мы не разглашаем данные наших пользователей</small>
                </div>
                <div class="form-group">
                    <label for="EmailTo">E-mail получателя</label>
                    {{ form.to }}
                </div>
                <div class="form-group">
                    <label for="comment">Комментарий</label>
                    {{ form.comment }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
                {% csrf_token %}
            </form>
        {% endif %}
    </div>
{% endblock %}

blog/templates/paginations.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Попередня</a>
        {% endif %}
        <span class="current">
            Сторінка {{page.number}} з {{page.paginator.num_pages}}.
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Наступна</a>
        {% endif %}
    </span>

</div>